import type { Metadata } from 'next';
import './globals.css';
import ClientLayout from '@/client-layout';

export const metadata: Metadata = {
  title: 'Dry run',
  description: 'Generated by create next app',
};

// DOS-inspired appearance settings using specified variables

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
