import type { Metadata } from 'next';
import { Press_Start_2P } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const pressStart2P = Press_Start_2P({
  weight: '400', // Specify the weight here
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Dry run',
  description: 'Generated by create next app',
};

const appearance = {
  variables: {
    colorPrimary: '#4C3A32', // Retro Brown
    colorBackground: '#F5D76E', // Retro Yellow
    colorText: '#4C3A32', // Retro Brown
    colorTextSecondary: '#3B5323', // Retro Green
    colorTextOnPrimaryBackground: '#FFFFFF', // White
    colorDanger: '#E74C3C', // Retro Red
    colorSuccess: '#3A5FCD', // Retro Blue
    colorWarning: '#D35400', // Retro Orange
    colorInputBackground: '#F5D76E', // Same as Retro Yellow for input background
    colorInputBorder: '#4C3A32', // Retro Brown
    colorInputText: '#4C3A32', // Retro Brown
    colorButtonText: '#FFFFFF', // White
    colorButtonBackground: '#3A5FCD', // Retro Blue
    colorButtonBorder: '#4C3A32', // Retro Brown
  },
  elements: {
    card: 'rounded-lg border-4 border-retroBrown bg-retroYellow shadow-lg p-4',
    headerTitle: 'text-4xl font-pixel text-retroBrown mb-6 text-center',
    formButtonPrimary:
      'bg-retroBlue text-white border-2 border-retroBrown shadow-[4px_4px_0px_#4c3a32] uppercase px-5 py-2',
    formFieldInput:
      'bg-retroYellow text-retroBrown border-2 border-retroBrown p-2 rounded-sm shadow-inner',
    footer: 'text-retroGray text-center mt-4',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${pressStart2P.className} min-h-screen flex items-center justify-center`}
      >
        <ClerkProvider appearance={appearance}>{children}</ClerkProvider>
      </body>
    </html>
  );
}
